DeveloperAcademy-POSTECH/MC3-Team6-HaKenLuRooCo

- TodayAnbu/Sources/Controllers/MainViewTopicController.swift
draft PR for sharing code to @Kim-Yeon-ho
> #3 feat: segmented control & refresh done

- TodayAnbu.xcodeproj/project.pbxproj
- TodayAnbu/Sources/Controllers/MainViewTopicController.swift
- TodayAnbu/Sources/SceneDelegate.swift
오토레이아웃 1차 수정 , 켄과 메인 뷰 화면 합치기 위한 pr
close #12
> #12 fix : 오토 레이아웃은 zoom모드 문제였음 레이아웃 수정함

- TodayAnbu.xcodeproj/project.pbxproj
- TodayAnbu/Sources/Controllers/MainViewController.swift
- TodayAnbu/Sources/SceneDelegate.swift
현재 까지 메인 뷰 작업본 합치기 작업
<br/>
메인 뷰 작업본 합쳤습니다.
ex) 작업시 참고한 자료가 있다면 추가해주세요!
- [작업내용](URL)
- [작업내용](URL)
<p>
<p/>
<br/>
ex) 리뷰받고 싶은 내용, 고민한 내용  등에 대해 적어주세요
- 코드 리펙토링에 관하여..ㅎ
> feat / 메인뷰 임시 합치는 작업

- TodayAnbu.xcodeproj/project.pbxproj
- TodayAnbu/Sources/Boards/UserInitSettingView.storyboard
- TodayAnbu/Sources/Controllers/UserInitViewController.swift
- TodayAnbu/Sources/Extensions/UITextfieldExtension.swift
userInfoSettingView의 Recfactor 및 userDefaults에 기본 정보 저장
<br/>
+ 다음 버튼을 누르면 유효성 판단 후, 전화번호를 userDefaults에 저장합니다.
+ 중복된 변수를 삭제했습니다.
+ 이전 version의 버그를 수정했습니다.
> 요일 선택기능은, 유효성 판단을 통해 전화번호가 완전히 입력되었을 때만 나타냅니다.
-> 한줄용 
<br/>
- 7개의 버튼 아악!!!
- 다른 뷰들과의 데이터 연동을 어떻게 할 지 궁금합니다.
> #7 [Feat]: connect UserDefaults & Code Refactor

- .github/auto_assign.yml
Auto Assign 입니다
<br/>
Auto Assign 구현
[블로그](https://lookingfor.tistory.com/entry/Github-auto-assign)
Closed #24
> #24 feat: add auto assign

- .github/auto_assign.yml
Auto assignee 가 reviewee 모두가 아닌 작성자로 시도
author 로 변경 시도
> #24 fix: take assignee a author

- TodayAnbu/Sources/Controllers/MainViewController.swift
켄 과 머지 후 코드를 정리했습니다.
린트에 총 코드 길이와 메소드안의 줄 갯수를 해제 해야할 것 같습니다.
<br/>
- 정리 잘 되었는지?!
> [refactor] : 코드정리

- TodayAnbu/Sources/Controllers/MainViewController.swift
체크 박스 Tapgesture 넣기
<br/>
Tapgesture를 넣어버렸습니다
Tapgesutre 구글링
https://user-images.githubusercontent.com/59143479/180104810-2c74af2c-38f5-4922-86b2-49e4217ebdf8.mp4
closed #40
> #40 attach UIImage TapGesture

- .github/workflows/build-test.yml
GitHub actions 가 작동되지 않는 오류를 수정중입니다
<br/>
임시적으로 develop 브렌치와 다른 사항만 적용하다가 전부 확인하는 것으로 바꿨습니다.
내 머리
Closed #57
> #57 fix: develop 브렌치와 다른 것만 Lint 적용 -> 모든 파일에 대하여

- TodayAnbu.xcodeproj/project.pbxproj
- TodayAnbu/Resources/Assets.xcassets/Colors/Contents.json
- TodayAnbu/Resources/Assets.xcassets/Colors/mainIndigo.colorset/Contents.json
- TodayAnbu/Sources/Controllers/MainViewController.swift
- TodayAnbu/Sources/Extensions/UIColor+Extension.swift
- TodayAnbu/Sources/Extensions/UITextfieldExtension.swift
공통적으로 색상을 커스텀하여 사용하기 위해 색상을 등록하고 바로 호출해서 쓸 수 있도록 했습니다.
<br/>
Color+Extension, Asset에 색상 추가
<br/>
- 색상 추가하는 방법을 아시면 좋을듯 합니다.
> #64 feature: Custom Color 도입

- .swiftlint.yml
- TodayAnbu/Resources/Assets.xcassets/Colors/dadDeepSkyblue.colorset/Contents.json
- TodayAnbu/Resources/Assets.xcassets/Colors/dadGaugeDeep.colorset/Contents.json
- TodayAnbu/Resources/Assets.xcassets/Colors/dadGaugeLight.colorset/Contents.json
- TodayAnbu/Resources/Assets.xcassets/Colors/dadLightSkyblue.colorset/Contents.json
- TodayAnbu/Resources/Assets.xcassets/Colors/mainTitleFontColor.colorset/Contents.json
- TodayAnbu/Resources/Assets.xcassets/Colors/mainTitleOrange.colorset/Contents.json
- TodayAnbu/Resources/Assets.xcassets/Colors/momDeepPink.colorset/Contents.json
- TodayAnbu/Resources/Assets.xcassets/Colors/momGaugeDeep.colorset/Contents.json
- TodayAnbu/Resources/Assets.xcassets/Colors/momGaugeLight.colorset/Contents.json
- TodayAnbu/Resources/Assets.xcassets/Colors/momLightPink.colorset/Contents.json
- TodayAnbu/Sources/AppDelegate.swift
- TodayAnbu/Sources/Controllers/MainViewController.swift
- TodayAnbu/Sources/Extensions/UIColor+Extension.swift
- TodayAnbu/Sources/SceneDelegate.swift
Color Set 추가, MainView내 topArea 삽입
<br/>
개요와 같습니다.
<br/>
- 색상과 topArea 영역의 사이즈가 적절한지
> Feature/63: MainDesign

- TodayAnbu/Sources/Controllers/MainViewController.swift
- TodayAnbu/Sources/SceneDelegate.swift
디자인 수정에 따른 메인화면 레이아웃 수정입니다.
tableView 백그라운드에 UIColor.black을 줘서 cell과 tableView의 차이를 봤습니다.
cell의 크기는 default 값이 44인 것은 알아냈습니다. 동적으로 cell의 크기를 바꾸다 보면 토픽마다 tableView가 달라져서
이상할 것 같은데 이에 대해 내일 얘기해보고 싶습니다.
close #66 
<br/>
메인 뷰 레이아웃에 따른 수정
-> 한줄용
<br/>
ex) 리뷰받고 싶은 내용, 고민한 내용  등에 대해 적어주세요
- 주석으로 처리 된 부분이 HuggingPriortiy과 dynamic cell size와 관련 된 부분인데 혹시 아시는 분 있으시면 도움 요청하겠습니다..
> Feature/66 refact main view controller (디자인 변경에 따른 메인 뷰 수정)

- .swiftlint.yml
- TodayAnbu.xcodeproj/project.pbxproj
- TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
- TodayAnbu/Sources/Boards/MemoStoryboard.storyboard
- TodayAnbu/Sources/Controllers/MainViewController.swift
- TodayAnbu/Sources/Controllers/MemoViewController.swift
- TodayAnbu/Sources/Models/MemoCell.swift
- TodayAnbu/Sources/Models/MemoData.swift
- TodayAnbu/Sources/SceneDelegate.swift
메모 뷰컨과 셀을 제작하였습니다.
<br/>
위와 동일
<br/>
ex) 리뷰받고 싶은 내용, 고민한 내용  등에 대해 적어주세요
- 생각하신 디자인이 맞나요? 숫자는 임시로 넣었는데 이게 생각대로인지
> Feature/78 memo UI

- TodayAnbu/Info.plist
- TodayAnbu/Sources/AppDelegate.swift
세로모드와 라이트 모드 고정
<br/>
- Appdelegate에서 세로모드 고정 코드를 작성하고
- Info.plist 에서 라이트 모드 고정을 시켰습니다
ex) 작업시 참고한 자료가 있다면 추가해주세요!
- [세로 모드 고정](https://declan.tistory.com/22)
- [라이트 모드 / 다크 모드 다루기](https://gyuios.tistory.com/120)
> #99 feat: 세로모드 & 라이트모드 고정

- TodayAnbu/Sources/Controllers/DadInitViewController.swift
- TodayAnbu/Sources/Controllers/MomInitViewController.swift
아빠 번호 입력되도록 수정
<br/>
- momPhoneNumber 에만 둘다 넣던 것 수정
- 불필요하게 빈 문자열로 초기화 하는 코드 삭제
- 사용하지 않는 isFirstLogin 삭제
> #113 fix: 아빠 번호 입력되도록 수정

- TodayAnbu/Sources/Controllers/MainViewController.swift
MainView의 Top rounded rectangle의 corner를 채웠습니다
<br/>
MainView의 Top rounded rectangle의 corner를 채웠습니다
Closed #116
> #116 fix: MainView Top Rounded Rectangle 채우기

- TodayAnbu.xcodeproj/project.pbxproj
- TodayAnbu/Resources/Assets.xcassets/Colors/memoColor.colorset/Contents.json
- TodayAnbu/Sources/Boards/MemoStoryboard.storyboard
- TodayAnbu/Sources/Controllers/MemoViewController.swift
- TodayAnbu/Sources/Extensions/UIColor+Extension.swift
메모 디자인 수정
<br/>
메모 디자인 현장에서 합의한 대로 수정했습니다.
<br/>
- 항목1
- 항목2
> feat: 메모를 디자인에 맞게 수정했습니다

- TodayAnbu/Sources/Controllers/CallCheckViewController.swift
- TodayAnbu/Sources/Controllers/MainViewController.swift
- TodayAnbu/Sources/Extensions/DateFormatting.swift
- TodayAnbu/Sources/Models/CallModelData.swift
전화 안할때 할때 날짜 카운트 하는 기능 추가
<br/>
전화 안할때 할때 날짜 카운트 하는 기능 추가
ex) 작업시 참고한 자료가 있다면 추가해주세요!
- [전화 카운트](https://github.com/DevKang)
ex) 리뷰받고 싶은 내용, 고민한 내용  등에 대해 적어주세요
- 다 해주세요
> [feat]  전화 카운트 시스템 온

- TodayAnbu/Sources/Controllers/MainViewController.swift
리뉴얼 버튼은 하디와 코지의 리젝을 먹었습니다...
<br/>
- topTitle 위치
> fix: 상단 타이틀 99일까지는 봐줄만하게 수정

- TodayAnbu.xcodeproj/project.pbxproj
- TodayAnbu/Sources/Boards/AboutUsView.storyboard
- TodayAnbu/Sources/Controllers/MainViewController.swift
- TodayAnbu/Sources/Controllers/SettingViewController.swift
- TodayAnbu/Sources/Models/SettingPersonalDataCell.swift
About Us 연결했습니다.
<br/>
테이블에 링크까지 완료했습니다.
-> 한줄용
<br/>
- 원하는 디자인으로 들어갔는지, 모달에서 네비게이션을 바로 연결했는데 보기 좋은지
> feat: AboutUs 통합 완료 & 새로고침버튼 수정 적용
